version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: aspnetcoreapi:latest
    ports:
      - "5000:80"
    volumes:
      - .:/src
      - ./db:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/db/mydb.sqlite
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/weatherforecast"] # Adjust this to a suitable endpoint
      interval: 10s # Healthcheck every 10 seconds
      timeout: 5s # Wait up to 5 seconds for a response
      retries: 5 # Retry up to 5 times before marking as unhealthy
      start_period: 20s # Give the app 20 seconds to start up
networks:
  app-network:
    driver: bridge
