services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aspnetcoreapi:latest
    ports:
      - "5000:80"
    volumes:
      - ./src:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SQLite=/app/db/mydb.sqlite
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet test /app/AspNetCoreApi.Tests/AspNetCoreApi.Tests.csproj
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
