version: "3.8"

services:
  polymorphicapi:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=polymorphicdb.db
    depends_on:
      - db

  db:
    image: nouchka/sqlite
    container_name: sqlite_db
    volumes:
      - polymorphicdb:/data

volumes:
  polymorphicdb:
